### ISSUE TITLE
ModuleNotFoundError: No module named 'grp'

### ISSUE THREAD

**Issue by sdementen** [lino-framework/lino#107]
hello,

Doing a fresh install of lino and running `getlino` I get a 
```
  File "c:\...\site-packages\getlino\configure.py", line 8, in <module>
    import grp
ModuleNotFoundError: No module named 'grp'
```

**Comment by lsaffre** [comment]
Indeed, Lino isn't meant to run on Windows. The [grp](https://docs.python.org/3/library/grp.html) module isn't available on Windows. At the moment we have no plans to make Lino installable on Windows. If you want to develop your own Lino application, you should anyway switch to Linux. But if you insist on Windows you are welcome to submit patches.
